name: fair_fare_app
description: A Flutter app for mapping routes, stops, and fare estimation.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.2.1

  # Maps & Location
  google_maps_flutter: ^2.7.0
  geolocator: ^11.0.0

  # State Management
  provider: ^6.1.2

  # Networking
  http: ^1.2.2

  # UI & Utilities
  cupertino_icons: ^1.0.6
  flutter_typeahead: ^5.2.0
  intl: ^0.20.2
  flutter_polyline_points: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
